### ISSUE TITLE
Allow use of `load` in Skylark when using Skyhook

### ISSUE THREAD

**Issue by garethr** [starlight-go/starlight#3]
The Skylark spec describes `load` (https://github.com/google/skylark/blob/master/doc/spec.md#load-statements) which allows for loading from other modules.

Using `load` in a Skylark file interpreted via Skyhook however results in the following error:

```
load not implemented by this application
```

This appears to be because Skylark binds load to the thread in the private `execfile` rather than the public `ExecFile` which is then used by Skyhook.

https://github.com/google/skylark/blob/6696fc363ddd14245a8d3b03e806e48703d1b23f/cmd/skylark/skylark.go#L92

Does Skyhook provide a mechanism for binding functions like this to users, and/or is this something that should be hooked up by default?

**Comment by natefinch** [comment]
Thanks for bringing this up.. sorry it got lost for so long.   I'm fixing this now.

**Comment by natefinch** [comment]
Fixed!  individual calls to Eval can now be passed your own load function (I may soon create a default "just find stuff from X directory" value to use), and the caching mechanism uses its own special load function to ...cache :)
